// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfOcA-3VQTlDeAtrfilZ0nuNytuaUi0YQ',
    appId: '1:245803244831:android:7e49200eea94b6b36ee42a',
    messagingSenderId: '245803244831',
    projectId: 'notes-8c5ab',
    storageBucket: 'notes-8c5ab.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwZw_QU4wSHSHU-D7vO0xqIknRfdBtF4M',
    appId: '1:245803244831:ios:8ad99864309ea3e16ee42a',
    messagingSenderId: '245803244831',
    projectId: 'notes-8c5ab',
    storageBucket: 'notes-8c5ab.firebasestorage.app',
    iosBundleId: 'com.example.firebaseUtilization',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdlHfaFaCail_0ue2HhTMMiPFsw1kSaJw',
    appId: '1:245803244831:web:636e8a0a0edab83d6ee42a',
    messagingSenderId: '245803244831',
    projectId: 'notes-8c5ab',
    authDomain: 'notes-8c5ab.firebaseapp.com',
    storageBucket: 'notes-8c5ab.firebasestorage.app',
    measurementId: 'G-KW97MJL88S',
  );
}
